name: Release build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Release build
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios
    
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
        with:
          submodules: false

      - name: Init submodules (full depth for nested submodules)
        run: |
          git submodule update --init --recursive

      - name: Install dependencies
        run: |
          export HOMEBREW_NO_ENV_HINTS=1
          command -v gmake &>/dev/null || brew install make
          command -v cmake &>/dev/null || brew install cmake
          command -v wget &>/dev/null || brew install wget
          command -v xz &>/dev/null || brew install xz
          /usr/libexec/java_home -v 1.8 &>/dev/null || brew install --cask zulu@8
          brew install libplist openssl 2>&1 | grep -v "already installed"
          command -v ldid &>/dev/null || {
            git clone --depth=1 https://github.com/ProcursusTeam/ldid.git
            cd ldid
            make -j$(sysctl -n hw.ncpu)
            sudo cp ldid /usr/local/bin/ldid
            cd ..
            rm -rf ldid
          }

      - name: Select Xcode version
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcrun --sdk iphoneos --show-sdk-path

      - name: Build for ${{ matrix.platform_name }}
        env:
          RELEASE: 1
        run: |
          export PATH=$(brew --prefix)/bin:$PATH
          export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
          export PATH=$JAVA_HOME/bin:$PATH
          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}

      - name: Upload regular ipa
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: org.angelauramc.amethyst-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst-*-${{ matrix.platform_name }}.ipa

      - name: Upload slimmed ipa
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: org.angelauramc.amethyst.slimmed-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst.slimmed-*-${{ matrix.platform_name }}.ipa

      - name: Upload dSYM
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: matrix.platform_name == 'ios'
        with:
          name: AngelAuraAmethyst.dSYM
          path: artifacts/AngelAuraAmethyst.dSYM
